spring:
  application:
    name: test-stand
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: test
    password: test
    pool:
      max-size: 100
  liquibase:
    url: jdbc:postgresql://localhost:5432/test
    user: test
    change-log: classpath:/database/changelog.yaml
    password: test

server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
  error:
    include-stacktrace: always
    include-message: always
#  tomcat:
#    threads:
#      max: 1 #In code!!!
#      min-spare: 1 #In code!!!!
#    accept-count: 100
#    processor-cache: 1
#    max-connections: 100



management:
  server:
    port:
      8081
  endpoints:
    web:
      exposure:
        include: 'info, health, prometheus'
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  swagger-ui:
    #config-url: "http://localhost:8080/test-stand/v3/api-docs"
    url: "http://localhost:8080/v3/api-docs"

logging:
  level:
    root: info
