spring:
  application:
    name: test-stand
  datasource:
    url: jdbc:tc:postgresql:11:///test
    username: test
    password: test
    hikari:
      maximum-pool-size: 100
  r2dbc:
    url: r2dbc:tc:postgresql:11:///test
    username: test
    password: test
  liquibase:
    change-log: classpath:/database/changelog.yaml

server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
  error:
    include-stacktrace: always
    include-message: always
  tomcat:
    threads:
      max: 1 #In code!!!
      min-spare: 1 #In code!!!!
    accept-count: 100
    processor-cache: 1
    max-connections: 100



management:
  server:
    port:
      8081
  endpoints:
    web:
      exposure:
        include: 'info, health, prometheus'
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  swagger-ui:
    #config-url: "http://localhost:8080/test-stand/v3/api-docs"
    url: "http://localhost:8080/test-stand/v3/api-docs"

logging:
  level:
    root: info
