spring:
  application:
    name: test-stand
  datasource:
    url: jdbc:tc:postgresql:11:///test
    #driver-class-name: #org.postgresql.Driver #org.testcontainers.jdbc.ContainerDatabaseDriver
    username: test
    password: test
  #jpa:
  #  generate-ddl: true
  #  hibernate:
  #    ddl-auto: create-drop
  liquibase:
    change-log: classpath:/database/changelog.yaml

server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
  error:
    include-stacktrace: always
    include-message: always
  tomcat:
#    threads:
#      max: 1 In code!!!
#      min-spare: 1 In code!!!!
    accept-count: 100
    processor-cache: 1
    max-connections: 100



management:
  server:
    port:
      8081
  endpoints:
    web:
      exposure:
        include: 'info, health, prometheus'#metrics, prometheus, heapdump, scheduledtasks, logfile, loggers, mappings'
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  swagger-ui:
    #config-url: "http://localhost:8080/test-stand/v3/api-docs"
    url: "http://localhost:8080/test-stand/v3/api-docs"

logging:
  level:
    root: info
